[package]
name = "wayfinder"
version = "0.1.0"
authors = ["Jordan McMichael <jlmcmchl@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0.104", features=["derive"] }
serde_derive = "1.0.104"
