[package]
name = "wayfinder"
version = "0.1.0"
authors = ["Jordan McMichael <jlmcmchl@gmail.com>"]
edition = "2018"

[dependencies]
nalgebra = "0.20.0"
serde = { version = "1.0.105", features=["derive"] }
serde_derive = "1.0.105"
